--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/stephen-mc-pl/UHC
build-by-default: true
branches:
- master
- pm4
projects:
  UHC:
    path: ""
    libs:
      - src: stephen-mc-pl/pmforms-pm4/pmforms
        branch: pm4
        version: 1.0.1
      - src: stephen-mc-pl/ScoreFactory/ScoreFactory
        branch: pm4
        version: 3.0.1
      - src: stephen-mc-pl/libChunkLoader/libChunkLoader
        branch: "4.0"
        version: 3.0.0
    lint:
      phpstan: false
...
