name: PHPStan

on: [push, pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pmforms
      uses: wei/wget@v1
      with:
        args: https://poggit.pmmp.io/r/96115/pmforms_dev-1.phar -O pmforms.phar
    - name: scorefactory
      uses: wei/wget@v1
      with:
        args: https://poggit.pmmp.io/r/95688/ScoreFactory_dev-12.phar -O ScoreFactory.phar
    - name: libchunkloader
      uses: wei/wget@v1
      with:
        args: https://poggit.pmmp.io/r/95685/libChunkLoader_dev-12.phar -O libChunkLoader.phar
    - name: ls
      run: ls
    - name: phpstan
      uses: nxtlvlsoftware/pmmp-phpstan-action@4
      with:
        phpstan-config: phpstan.neon.dist