name: PHPStan

on: [push, pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pmforms
      uses: wei/wget@v1
      with:
        args: -O pmforms.phar https://poggit.pmmp.io/r/55533/pmforms_dev-4.phar
    - name: scorefactory
      uses: wei/wget@v1
      with:
        args: -O ScoreFactory.phar https://poggit.pmmp.io/r/95688/ScoreFactory_dev-12.phar
    - name: libchunkloader
      uses: wei/wget@v1
      with:
        args: -O libChunkLoader.phar https://poggit.pmmp.io/r/95685/libChunkLoader_dev-12.phar
    - name: ls
      run: ls
    - name: phpstan
      uses: nxtlvlsoftware/pmmp-phpstan-action@4
      with:
        phpstan-config: phpstan.neon.dist