name: PHPStan

on: [push, pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: virions
      run: mkdir virions
    - name: pmforms
      uses: wei/wget@v1
      with:
        args: -P virions/ https://poggit.pmmp.io/r/55533/pmforms_dev-4.phar
    - name: scorefactory
      uses: wei/wget@v1
      with:
        args: -P virions/ https://poggit.pmmp.io/r/95687/ScoreFactory_dev-11.phar
    - name: libchunkloader
      uses: wei/wget@v1
      with:
        args: -P virions/ https://poggit.pmmp.io/r/95686/libChunkLoader_dev-13.phar
    - name: phpstan
      uses: nxtlvlsoftware/pmmp-phpstan-action@3
      with:
        phpstan-config: phpstan.neon.dist
