name: PHPStan

on: [push, pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: vendor dir
      run: mkdir vendor
    - name: pmforms
      uses: wei/wget@v1
      with:
        args: -P vendor/ https://poggit.pmmp.io/r/55533/pmforms_dev-4.phar
    - name: scorefactory
      uses: wei/wget@v1
      with:
        args: -P vendor/ https://poggit.pmmp.io/r/86613/ScoreFactory_dev-2.phar
    - name: phpstan
      uses: nxtlvlsoftware/pmmp-phpstan-action@3
      with:
        phpstan-config: phpstan.neon.dist
